name:                elocalc
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/elocalc#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5

executable: 
  main: Main.hs
  source-dirs:
    - app
  dependencies:
    - elocalc
    - persistent-postgresql
    - wai
    - warp
    - monad-logger
    - safe

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - containers
    - ekg
    - ekg-core
    - fast-logger
    - foreign-store
    - katip >= 0.5.0.2 && < 0.6
    - microlens
    - monad-control
    - monad-logger
    - monad-metrics
    - mtl
    - persistent
    - persistent-postgresql
    - persistent-template
    - safe
    - servant >= 0.13 && < 0.14
    - servant-js >= 0.9 && < 0.10
    - servant-server >= 0.13 && < 0.14
    - servant-swagger
    - text
    - transformers
    - unordered-containers
    - wai
    - wai-extra
    - wai-middleware-metrics
    - warp
    - resource-pool
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - random
      - elocalc
