name:                elocalc
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/elocalc#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  elocalc:
    source-dirs:      src
    main:             Main.hs

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - temporary
      - mockery >= 0.3
      - interpolate
      - template-haskell
      - HUnit >= 1.6.0.0
      - yaml >= 0.0.28
      - random
